# Generated by Django 4.2.4 on 2023-09-08 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_admin_hire_date_alter_order_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="hire_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 8, 21, 34, 57, 773033)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 8, 21, 34, 57, 773033)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Delivered", "Delivered"),
                    ("Declined", "Declined"),
                    ("Pending", "Pending"),
                    ("Shipped", "Shipped"),
                    ("Approved", "Approved"),
                ],
                max_length=20,
            ),
        ),
    ]
