# Generated by Django 4.2.4 on 2023-09-10 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_alter_category_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderdetails",
            options={
                "verbose_name": "Order Detail",
                "verbose_name_plural": "Orders Details",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="admin",
            name="hire_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 10, 19, 11, 6, 714874)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 10, 19, 11, 6, 715373)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Declined", "Declined"),
                    ("Approved", "Approved"),
                    ("Pending", "Pending"),
                ],
                max_length=20,
            ),
        ),
    ]
