# Generated by Django 4.2.4 on 2023-09-10 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_alter_admin_hire_date_alter_order_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="hire_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 10, 23, 53, 55, 858621)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 10, 23, 53, 55, 859318)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Declined", "Declined"),
                    ("Delivered", "Delivered"),
                    ("Shipped", "Shipped"),
                    ("Approved", "Approved"),
                ],
                max_length=20,
            ),
        ),
    ]
