# Generated by Django 4.2.4 on 2023-09-11 08:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_product_img_url_alter_admin_hire_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="hire_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 11, 11, 4, 8, 112558)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 11, 11, 4, 8, 112558)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Declined", "Declined"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Approved", "Approved"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderdetails",
            name="ordered_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="product",
            name="category_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="website.category",
            ),
        ),
    ]
